---
# 
# This playbook deploys CEDAR
# 
- name: Setup Working Directories
  sudo: yes
  file: path=/usr/lib/glossolalia state=directory mode=777

- name: Upload Release File
  unarchive: src=../../cedar/rel/cedar/cedar-0.0.1.tar.gz
             dest=/usr/lib/ohc/cedar

