---
#
# This playbook deploys Cedar
#
- name: Setup Working Directories
  sudo: yes
  file: path=/usr/lib/ohc/cedar
        state=directory
        mode=755
        owner=ubuntu

- name: Download Release
  get_url: url=https://github.com/openhealthcare/releases/blob/master/cedar/cedar-{{ cedar_version }}.tar.gz?raw=true
           dest=/usr/lib/ohc/cedar/cedar-{{ cedar_version }}.tar.gz
           mode=644

- name: Unpack Release
  unarchive: src=/usr/lib/ohc/cedar/cedar-{{ cedar_version }}.tar.gz
             dest=/usr/lib/ohc/cedar/
             copy=no

- name: Upload upstart conf
  sudo: yes
  copy: src=cedar.conf
        dest=/etc/init/cedar.conf
        mode=644
        owner=root
  notify:
      - Restart Cedar

