---
#
# This playbook deploys Glossolalia
#
- name: Setup Working Directories
  sudo: yes
  file: path=/usr/lib/ohc/glossolalia
        state=directory
        mode=755
        owner=ubuntu

- name: Download Release
  get_url: url=https://github.com/openhealthcare/releases/blob/master/glossolalia/glossolalia-{{ glossolalia_version }}.tar.gz?raw=true
           dest=/usr/lib/ohc/glossolalia/glossolalia-{{ glossolalia_version }}.tar.gz
           mode=644

- name: Unpack Release
  unarchive: src=/usr/lib/ohc/glossolalia/glossolalia-{{ glossolalia_version }}.tar.gz
             dest=/usr/lib/ohc/glossolalia/
             copy=no

- name: Upload upstart conf
  sudo: yes
  copy: src=glossolalia.conf
        dest=/etc/init/glossolalia.conf
        mode=644
        owner=root
  notify:
      - Restart Glossolalia

